DROP TABLE O_EREDMENYEK purge;
DROP TABLE O_VERSENYSZAMOK purge;
DROP TABLE O_SPORTAGAK purge;
DROP TABLE O_CSAPATTAGOK purge;
DROP TABLE O_VERSENYZOK purge;
DROP TABLE O_EREM_TABLA purge;
DROP TABLE O_ORSZAGOK purge;

CREATE TABLE O_ORSZAGOK
   (	AZON NUMBER(5), 
	ORSZAG VARCHAR2(50), 
	TERULET NUMBER(10), 
	LAKOSSAG NUMBER(10), 
	FOVAROS VARCHAR2(40),
        FOLDRESZ VARCHAR2(50), 
	 CONSTRAINT O_ORSZ_PK PRIMARY KEY (AZON),
         CONSTRAINT O_ORSZ_UK_ORSZ UNIQUE (ORSZAG));
  
CREATE TABLE O_EREM_TABLA
   (	ORSZAG_AZON NUMBER(5), 
	ARANY NUMBER(2), 
	EZUST NUMBER(2), 
	BRONZ NUMBER(2), 
	 CONSTRAINT O_ET_PK PRIMARY KEY (ORSZAG_AZON),
  	 CONSTRAINT O_ET_FK FOREIGN KEY (ORSZAG_AZON)
	      REFERENCES O_ORSZAGOK (AZON));
 
CREATE TABLE O_VERSENYZOK
    (  AZON NUMBER(5),
       NEV VARCHAR2(50),
       SZUL_DAT DATE,
       ORSZAG_AZON NUMBER(5),
       EGYEN_CSAPAT VARCHAR2(1),
       SZUL_HELY VARCHAR2(50),
        CONSTRAINT O_VERS_PK PRIMARY KEY(AZON),
        CONSTRAINT O_VNY_UK UNIQUE (NEV,ORSZAG_AZON,SZUL_DAT),
        CONSTRAINT O_VERS_FK_ORSZ FOREIGN KEY (ORSZAG_AZON)
             REFERENCES O_ORSZAGOK (AZON) );
          
  CREATE TABLE O_CSAPATTAGOK
   (	VERSENYZO_AZON NUMBER(5), 
	CSAPAT_AZON NUMBER(5), 
	 CONSTRAINT O_CST_PK PRIMARY KEY (VERSENYZO_AZON, CSAPAT_AZON), 
	 CONSTRAINT O_CST_FK_CS FOREIGN KEY (CSAPAT_AZON)
	          REFERENCES O_VERSENYZOK (AZON), 
	 CONSTRAINT O_CST_FK_T FOREIGN KEY (VERSENYZO_AZON)
	          REFERENCES O_VERSENYZOK (AZON));
          
  CREATE TABLE O_SPORTAGAK
   (	AZON NUMBER(5), 
	NEV VARCHAR2(50), 
	 CONSTRAINT O_SPAG_PK PRIMARY KEY (AZON),
  	 CONSTRAINT O_SPAG_UK UNIQUE (NEV));
        
   CREATE TABLE O_VERSENYSZAMOK 
   (	AZON NUMBER(5), 
	SPORTAG_AZON NUMBER(5), 
	VERSENYSZAM VARCHAR2(50), 
	FERFI_NOI VARCHAR2(5), 
	 CONSTRAINT O_VSZAM_PK PRIMARY KEY (AZON),
  	 CONSTRAINT O_VSZAM_UK UNIQUE (SPORTAG_AZON, VERSENYSZAM, FERFI_NOI),
  	 CONSTRAINT O_VSZAM_FK_SP FOREIGN KEY (SPORTAG_AZON)
	  REFERENCES O_SPORTAGAK (AZON));

CREATE TABLE O_EREDMENYEK
   (   VERSENYZO_AZON NUMBER(5),
       VERSENYSZAM_AZON NUMBER(5),
       HELYEZES NUMBER(3),
       MEGJEGYZES VARCHAR2(150),
        CONSTRAINT O_E_PK PRIMARY KEY  (VERSENYZO_AZON, VERSENYSZAM_AZON),
        CONSTRAINT O_E_FK_VSZ FOREIGN KEY ( VERSENYSZAM_AZON)
                  REFERENCES O_VERSENYSZAMOK (AZON),
        CONSTRAINT O_E_FK_VNY FOREIGN KEY (VERSENYZO_AZON)
                  REFERENCES O_VERSENYZOK (AZON) );


