insert into o_sportagak (AZON,NEV) values (301,'Asztalitenisz');                                                                           
insert into o_sportagak (AZON,NEV) values (302,'Labdarúgás');                                                                              
insert into o_sportagak (AZON,NEV) values (303,'Szinkronúszás');                                                                           
insert into o_sportagak (AZON,NEV) values (304,'Atlétika');                                                                                
insert into o_sportagak (AZON,NEV) values (305,'Lovaglás');                                                                                
insert into o_sportagak (AZON,NEV) values (306,'Tékvandó');                                                                                
insert into o_sportagak (AZON,NEV) values (307,'Baseball');                                                                                
insert into o_sportagak (AZON,NEV) values (308,'Lövészet');                                                                                
insert into o_sportagak (AZON,NEV) values (309,'Tenisz');                                                                                  
insert into o_sportagak (AZON,NEV) values (310,'Birkózás');                                                                                
insert into o_sportagak (AZON,NEV) values (311,'Műugrás');                                                                                 
insert into o_sportagak (AZON,NEV) values (312,'Tollaslabda');                                                                             
insert into o_sportagak (AZON,NEV) values (313,'Cselgáncs');                                                                               
insert into o_sportagak (AZON,NEV) values (314,'Országúti kerékpár');                                                                      
insert into o_sportagak (AZON,NEV) values (315,'Torna');                                                                                   
insert into o_sportagak (AZON,NEV) values (316,'Evezés');                                                                                  
insert into o_sportagak (AZON,NEV) values (317,'Ökölvívás');                                                                               
insert into o_sportagak (AZON,NEV) values (318,'Trampolin');                                                                               
insert into o_sportagak (AZON,NEV) values (319,'Gyeplabda');                                                                               
insert into o_sportagak (AZON,NEV) values (320,'Öttusa');                                                                                  
insert into o_sportagak (AZON,NEV) values (321,'Triatlon');                                                                                
insert into o_sportagak (AZON,NEV) values (322,'Hegyi kerékpár');                                                                          
insert into o_sportagak (AZON,NEV) values (323,'Pályakerékpár');                                                                           
insert into o_sportagak (AZON,NEV) values (324,'Úszás');                                                                                   
insert into o_sportagak (AZON,NEV) values (325,'Íjászat');                                                                                 
insert into o_sportagak (AZON,NEV) values (326,'Ritmikus sportgimnasztika');                                                               
insert into o_sportagak (AZON,NEV) values (327,'Vitorlázás');                                                                              
insert into o_sportagak (AZON,NEV) values (328,'Kajak-kenu');                                                                              
insert into o_sportagak (AZON,NEV) values (329,'Röplabda');                                                                                
insert into o_sportagak (AZON,NEV) values (330,'Vívás');                                                                                   
insert into o_sportagak (AZON,NEV) values (331,'Kajak-szlalom');                                                                           
insert into o_sportagak (AZON,NEV) values (332,'Softball');                                                                                
insert into o_sportagak (AZON,NEV) values (333,'Vízilabda');                                                                               
insert into o_sportagak (AZON,NEV) values (334,'Kézilabda');                                                                               
insert into o_sportagak (AZON,NEV) values (335,'Strandröplabda');                                                                          
insert into o_sportagak (AZON,NEV) values (336,'Kosárlabda');                                                                              
insert into o_sportagak (AZON,NEV) values (337,'Súlyemelés');     
commit;
